### ISSUE TITLE
Run serenity tests in AWS codePipeline 

### ISSUE THREAD

**Issue by prashantrbs** [serenity-bdd/serenity-core#3080]
Hi There,

i want to run my serenity BDD tests in aws codePipeline but i am not sure how to download and required dependencies in prebuild phase.

i have the below buildspec.yml file this will successfully executes API tests but UI tests are not executing as chrome driver and chrome is not installed. can someone give a sample buildspec.yml file that can download the required dependencies and then run API and Ui tests?

**buildspec.yml**
```
version: 0.2

phases:
  build:
    commands:
      - mvn clean verify "-Dtest.env=stage"
```
